/**
 * Category mappings for different book types
 */

export const SCHOOL_CATEGORIES = [
  "Accounting",
  "Afrikaans",
  "Agricultural Management",
  "Agricultural Sciences",
  "Ancient Languages",
  "Animal Husbandry",
  "Architecture",
  "Art & Design",
  "Arts & Humanities",
  "Astronomy",
  "Automotive",
  "Bacteriology",
  "Biology",
  "Business Management",
  "Business Studies",
  "Career Guidance",
  "Chemistry",
  "Chinese",
  "Clothing & Textiles",
  "Communication",
  "Computer Applications",
  "Computer Programming",
  "Consumer Studies",
  "Cosmetology",
  "Dance",
  "Design & Technology",
  "Economics",
  "Education",
  "Electrical Engineering",
  "Electronic Media",
  "Electronics",
  "Engineering",
  "Engineering Graphics",
  "English",
  "English Language & Literature",
  "Environmental Management",
  "Environmental Studies",
  "Family & Consumer Sciences",
  "Fashion Design",
  "Film & Media",
  "Finance",
  "Food Technology",
  "Foreign Languages",
  "French",
  "Furniture Making",
  "Geography",
  "German",
  "Global Citizenship",
  "Government & Politics",
  "Graphic Design",
  "Greek",
  "Hair & Beauty",
  "Health & Safety",
  "Health Science",
  "Hindi",
  "History",
  "Home Economics",
  "Hospitality & Tourism",
  "Hotel Management",
  "Human Physiology",
  "Humanities",
  "ICT / IT",
  "Industrial Management",
  "Information Technology",
  "Instrumentation",
  "Interiors & Furnishings",
  "Japanese",
  "Journalism",
  "Labour Relations",
  "Latin",
  "Law",
  "Leadership & Management",
  "Library & Information Science",
  "Life Orientation",
  "Life Sciences",
  "Languages",
  "Literature",
  "Logistics",
  "Maintenance & Management",
  "Management",
  "Manufacturing",
  "Marine Biology",
  "Marketing",
  "Mathematics",
  "Mechanical Engineering",
  "Mechanics",
  "Media Studies",
  "Medical Science",
  "Medicine",
  "Merchandising",
  "Metallurgy",
  "Microbiology",
  "Mining",
  "Modern European Studies",
  "Modern Greek",
  "Modern Languages",
  "Modern Zulu",
  "Molecular Biology",
  "Money Management",
  "Morphology",
  "Music",
  "Musicology",
  "Mythology",
  "National Schools Curriculum",
  "Nature Conservation",
  "Natural Sciences",
  "Navigation",
  "Ndebele",
  "Nursing",
  "Office Management",
  "Occupational Health & Safety",
  "Operations Management",
  "Optics",
  "Organisation & Management",
  "Organisational Development",
  "Oriental Languages",
  "Ornithology",
  "Pharmacology",
  "Philosophy",
  "Physical Education",
  "Physical Science",
  "Physics",
  "Physiology",
  "Plant Science",
  "Plumbing",
  "Poetry & Drama",
  "Political Science",
  "Politics",
  "Portuguese",
  "Powder Metallurgy",
  "Psychology",
  "Public Administration",
  "Public Health",
  "Public Speaking",
  "Publishing",
  "Quality Assurance",
  "Quantitative Methods",
  "Quantity Surveying",
  "Radiotherapy",
  "Radio & Television",
  "Railway Studies",
  "Real Estate",
  "Recreation & Leisure",
  "Religious Studies",
  "Religious Education",
  "Research Methodology",
  "Respiratory Therapy",
  "Retailing",
  "Rock Climbing",
  "Russian",
  "Safety & Health",
  "Sales Management",
  "Sanskrit",
  "Science",
  "Science & Technology",
  "Sea Studies",
  "Secretarial Studies",
  "Securities",
  "Self-Defence",
  "Sepedi",
  "Sesotho",
  "Setswana",
  "Shona",
  "Sign Language",
  "Sikhism",
  "Social Development",
  "Social Sciences",
  "Social Studies",
  "Sociology",
  "Spanish",
  "Special Education",
  "Speech & Language Pathology",
  "Sport & Recreation",
  "Sport Management",
  "Sports Science",
  "Staining & Polishing",
  "Standard Grade Studies",
  "Statistics",
  "Stenography",
  "Store Management",
  "Strategic Management",
  "Strategies for Learning",
  "Structural Design",
  "Studies in Religion",
  "Study Skills",
  "Supply Chain Management",
  "Sustainable Development",
  "Swahili",
  "Swedish",
  "Systems Administration",
  "Systems Analysis",
  "Taxation",
  "Teaching & Learning",
  "Technical Drawing",
  "Technical Graphics",
  "Technology",
  "Telecommunications",
  "Textile Design",
  "Textile Technology",
  "Thai",
  "Theatre",
  "Theology",
  "Theory of Knowledge",
  "Tourism",
  "Tourism Management",
  "Track Management",
  "Transport Management",
  "Travel & Tourism",
  "Trigonometry",
  "Turkish",
  "Typing & Keyboard",
  "Understanding Differences",
  "Urban & Regional Planning",
  "Urban Planning",
  "Veterinary Science",
  "Vietnamese",
  "Virology",
  "Visual Arts",
  "Viticulture",
  "Vocational & Technical Studies",
  "Waste Management",
  "Water Resources",
  "Wear & Tear",
  "Weaving",
  "Web Design & Development",
  "Wedding Planning",
  "Welding",
  "Wells & Boreholes",
  "Winemaking",
  "Wood Science",
  "Woodwork",
  "Working with Children",
  "Workplace Communication",
  "World Geography",
  "World History",
  "World Literature",
  "World Religions",
  "Writing",
  "Xhosa",
  "Yoga",
  "Youth & Community Development",
  "Zoology",
  "Zulu",
];

export const UNIVERSITY_CATEGORIES = [
  "Accounting",
  "Actuarial Science",
  "Administration",
  "Advertising",
  "Aeronautical Engineering",
  "African Studies",
  "Agricultural Economics",
  "Agricultural Engineering",
  "Agricultural Sciences",
  "Agronomy",
  "Algorithms",
  "American Studies",
  "Anatomy",
  "Ancient History",
  "Ancient Languages",
  "Animal Science",
  "Anthropology",
  "Applied Linguistics",
  "Applied Mathematics",
  "Archaeology",
  "Architecture",
  "Area Studies",
  "Art",
  "Art History",
  "Arts",
  "Asian Studies",
  "Astronomy",
  "Astrophysics",
  "Atmospheric Sciences",
  "Audiology",
  "Australian Indigenous Studies",
  "Australian Studies",
  "Automotive Engineering",
  "Aviation",
  "Bacteriology",
  "Banking",
  "Behavioral Science",
  "Biochemistry",
  "Bioethics",
  "Bioinformatics",
  "Biological Engineering",
  "Biological Sciences",
  "Biology",
  "Biomedical Engineering",
  "Biomedical Science",
  "Biophysics",
  "Biotechnology",
  "Black Studies",
  "Botany",
  "Broadcast Journalism",
  "Broadcasting",
  "Building & Construction",
  "Building Technology",
  "Business",
  "Business Administration",
  "Business Analytics",
  "Business Economics",
  "Business Information Systems",
  "Business Management",
  "Business Studies",
  "Business Systems",
  "Chemical Engineering",
  "Chemistry",
  "Chinese",
  "Chinese Studies",
  "Cinema Studies",
  "Civil Engineering",
  "Classical Languages",
  "Classical Studies",
  "Clinical Psychology",
  "Commercial Law",
  "Communication",
  "Communication Studies",
  "Community Development",
  "Community Health",
  "Community Psychology",
  "Comparative Literature",
  "Computational Biology",
  "Computational Chemistry",
  "Computational Physics",
  "Computer Engineering",
  "Computer Graphics",
  "Computer Networks",
  "Computer Science",
  "Computing",
  "Conflict Resolution",
  "Conservation Biology",
  "Construction Management",
  "Consumer Psychology",
  "Contemporary History",
  "Control Systems",
  "Corporate Finance",
  "Corporate Law",
  "Corporate Social Responsibility",
  "Counseling Psychology",
  "Cosmetics",
  "Counseling",
  "Criminology",
  "Critical Care Nursing",
  "Cultural Anthropology",
  "Cultural Studies",
  "Curatorial Studies",
  "Curriculum & Instruction",
  "Cybersecurity",
  "Dairy Science",
  "Dance",
  "Data Analytics",
  "Data Science",
  "Database Management",
  "Demography",
  "Dental Hygiene",
  "Dentistry",
  "Design",
  "Design Technology",
  "Development Economics",
  "Developmental Biology",
  "Developmental Psychology",
  "Dietetics",
  "Diplomacy",
  "Digital Art",
  "Digital Design",
  "Digital Media",
  "Digital Telecommunications",
  "Directed Studies",
  "Disability Studies",
  "Discrete Mathematics",
  "Disease Ecology",
  "Distributed Systems",
  "Diversity & Inclusion",
  "Drama",
  "Drama & Theatre",
  "Drawing",
  "Dyslexia Studies",
  "Earth & Planetary Sciences",
  "Earth Science",
  "Ecology",
  "Economics",
  "Education",
  "Education Policy",
  "Educational Administration",
  "Educational Leadership",
  "Educational Psychology",
  "Educational Technology",
  "Electrical Engineering",
  "Electrical Systems",
  "Electronics",
  "Elementary Education",
  "Emergency Management",
  "Emergency Medicine",
  "Emerging Markets",
  "Emerging Media",
  "Employment Relations",
  "Energy Engineering",
  "Engineering",
  "Engineering Physics",
  "English",
  "English as a Second Language",
  "English Language & Literature",
  "English Literature",
  "Entomology",
  "Environmental Analysis",
  "Environmental Chemistry",
  "Environmental Economics",
  "Environmental Engineering",
  "Environmental Ethics",
  "Environmental Health",
  "Environmental Law",
  "Environmental Management",
  "Environmental Policy",
  "Environmental Science",
  "Environmental Sciences",
  "Environmental Studies",
  "Epidemiology",
  "Epistemology",
  "Ethnobiology",
  "Ethnography",
  "Ethnomusicology",
  "European History",
  "European Languages",
  "European Studies",
  "Events Management",
  "Exercise Science",
  "Existential Philosophy",
  "Experimental Physics",
  "Expert Systems",
  "Exploration & Paleontology",
  "Expository Writing",
  "Facilities Management",
  "Family Law",
  "Family Psychology",
  "Family Therapy",
  "Fashion",
  "Fashion Design",
  "Fashion Management",
  "Fashion Marketing",
  "Film & Media Studies",
  "Film & Video Production",
  "Film Production",
  "Film Studies",
  "Finance",
  "Financial Accounting",
  "Financial Economics",
  "Financial Engineering",
  "Financial Management",
  "Financial Mathematics",
  "Financial Planning",
  "Fine Art",
  "Fine Arts",
  "Fisheries Science",
  "Fitness Management",
  "Flight Operations",
  "Fluid Dynamics",
  "Food Business Management",
  "Food Chemistry",
  "Food Engineering",
  "Food Microbiology",
  "Food Science",
  "Food Science & Nutrition",
  "Food Technology",
  "Forensic Accounting",
  "Forensic Anthropology",
  "Forensic Biology",
  "Forensic Chemistry",
  "Forensic Science",
  "Forestry",
  "Forestry Science",
  "French",
  "French Studies",
  "Fund Management",
  "Functional Linguistics",
  "Functional Programming",
  "Game Design",
  "Game Development",
  "Gaming",
  "Gastroenterology",
  "Gender Studies",
  "Gene Therapy",
  "General Engineering",
  "General Medicine",
  "General Practice",
  "General Studies",
  "Generative Linguistics",
  "Genetic Counseling",
  "Genetic Engineering",
  "Genetics",
  "Genomics",
  "Geochemistry",
  "Geography",
  "Geoinformatics",
  "Geology",
  "Geomatics",
  "Geometry",
  "Geomorphology",
  "Geophysics",
  "Geopolitics",
  "German",
  "German Studies",
  "Gerontology",
  "Gerontological Nursing",
  "Gestalt Therapy",
  "Global Business",
  "Global Citizenship",
  "Global Economics",
  "Global Health",
  "Global History",
  "Global Politics",
  "Global Studies",
  "Global Trade",
  "Globalization Studies",
  "Government",
  "Government & Politics",
  "Graphic Communication",
  "Graphic Design",
  "Graphic Illustration",
  "Graphics & Visualization",
  "Greek",
  "Greek Civilization",
  "Greek History",
  "Green Building",
  "Green Energy",
  "Groundwater Engineering",
  "Group Psychology",
  "Growth & Development",
  "Guidance & Counseling",
  "Hair & Beauty Management",
  "Hand Therapy",
  "Hardware Engineering",
  "Health Administration",
  "Health Care Administration",
  "Health Care Law",
  "Health Economics",
  "Health Education",
  "Health Informatics",
  "Health Management",
  "Health Policy",
  "Health Psychology",
  "Health Sciences",
  "Health Service Administration",
  "Healthcare Management",
  "Hearing Science",
  "Hebrew",
  "Heritage Studies",
  "Hidden Markov Models",
  "High Energy Physics",
  "Hindi",
  "Hispanic Studies",
  "Historical Geography",
  "Historical Linguistics",
  "Historical Perspectives",
  "Historical Theology",
  "History",
  "History & Philosophy of Science",
  "History & Politics",
  "History of Africa",
  "History of America",
  "History of Architecture",
  "History of Art",
  "History of Asia",
  "History of the Caribbean",
  "History of Computing",
  "History of Design",
  "History of Education",
  "History of Europe",
  "History of Law",
  "History of Mathematics",
  "History of Medicine",
  "History of Middle East",
  "History of Music",
  "History of Philosophy",
  "History of Physics",
  "History of Religion",
  "History of Science",
  "History of Technology",
  "History of the Pacific",
  "Holistic Health",
  "Holistic Nursing",
  "Home Economics",
  "Home Management",
  "Homeland Security",
  "Homeopathy",
  "Horticulture",
  "Horticulture Science",
  "Hospitality",
  "Hospitality Management",
  "Hotel Administration",
  "Hotel Management",
  "Housing",
  "Housing & Community Development",
  "Human & Social Biology",
  "Human Anatomy",
  "Human Development",
  "Human Factors Engineering",
  "Human Genetics",
  "Human Geography",
  "Human Immunology",
  "Human Kinetics",
  "Human Nutrition",
  "Human Physiology",
  "Human Resource Management",
  "Human Resource Planning",
  "Human Resources",
  "Human Resources Development",
  "Human Rights",
  "Human Rights Law",
  "Humanities",
  "Humanities & Social Sciences",
  "Humanities Studies",
  "Hydrobiology",
  "Hydrology",
  "Hydropower Engineering",
  "Hygiene",
  "Hypertension",
  "Hypnotherapy",
  "Iberian Studies",
  "Ichthyology",
  "Icon & Orthodox Studies",
  "Iconography",
  "ICT",
  "Image Analysis",
  "Image Processing",
  "Imagery",
  "Imaginative Writing",
  "Immigration Law",
  "Immigration Studies",
  "Immunology",
  "Impact Studies",
  "Imperialism",
  "Implementation Studies",
  "Implicate Logic",
  "Implied Consent Law",
  "Implied Covenant",
  "Implied Metaphor",
  "Implied Meaning",
  "Implied Reader",
  "Implied Warranty",
  "Imply Studies",
  "Impolite Studies",
  "Importable Studies",
  "Importance Psychology",
  "Importance Studies",
  "Important Law",
  "Important Politics",
  "Important Psychology",
  "Important Studies",
  "Importer Studies",
  "Importer Economics",
  "Importer Law",
  "Importers & Exporters",
  "Imported Materials",
  "Imported Studies",
  "Imported Technology",
  "Importation Studies",
  "Impost Studies",
  "Impossible Studies",
  "Imposture Studies",
  "Impotence Studies",
  "Impotent Studies",
  "Impoundment Studies",
  "Impoverishment Studies",
  "Impractical Studies",
  "Imprecation Studies",
  "Imprecise Studies",
  "Impregnable Studies",
  "Impregnation Studies",
  "Impresario Studies",
  "Impression Studies",
  "Impressionism",
  "Imprimatur Studies",
  "Imprint Studies",
  "Imprisonment Studies",
  "Improbability",
  "Improbable Studies",
  "Impromptu Studies",
  "Improper Studies",
  "Impropriety Studies",
  "Improve Studies",
  "Improvement Studies",
  "Improvidence Studies",
  "Improvident Studies",
  "Improvisation",
  "Improvise Studies",
  "Imprudence Studies",
  "Imprudent Studies",
  "Impudence Studies",
  "Impudent Studies",
  "Impugn Studies",
  "Impulse Studies",
  "Impulsive Studies",
  "Impunity Studies",
  "Impure Studies",
  "Impurity Studies",
  "Imputable Studies",
  "Imputation Studies",
  "Impute Studies",
  "Inability Studies",
  "Inaccessibility Studies",
  "Inaccessible Studies",
  "Inaccuracy Studies",
  "Inaccurate Studies",
  "Inaction Studies",
  "Inactivate Studies",
  "Inactive Studies",
  "Inactivity Studies",
  "Inadequacy Studies",
  "Inadequate Studies",
  "Inadmissibility Studies",
  "Inadmissible Studies",
  "Inadvertence Studies",
  "Inadvertent Studies",
  "Inadvisability Studies",
  "Inadvisable Studies",
  "Inane Studies",
  "Inanimate Studies",
  "Inanition Studies",
  "Inapplicability Studies",
  "Inapplicable Studies",
  "Inapposite Studies",
  "Inappropriate Studies",
  "Inapt Studies",
  "Inaptitude Studies",
  "Inarch Studies",
  "Inarticular Studies",
  "Inarticulate Studies",
  "Inartistic Studies",
  "Inartistically Studies",
  "Inasbrace Studies",
  "Inasmuch Studies",
  "Inattack Studies",
  "Inattention Studies",
  "Inattentive Studies",
  "Inaudible Studies",
  "Inaugural Studies",
  "Inaugurate Studies",
  "Inauguration Studies",
  "Inauspicial Studies",
  "Inauspicious Studies",
  "Inaugurator Studies",
];

export const READER_CATEGORIES = [
  "Fiction",
  "Mystery & Thriller",
  "Science Fiction",
  "Fantasy",
  "Romance",
  "Adventure",
  "Historical Fiction",
  "Horror",
  "Young Adult",
  "Children's Books",
  "Self-Help",
  "Wellness & Mind",
  "Fitness & Health",
  "Memoir & Biography",
  "History",
  "Science",
  "Business & Economics",
  "Technology",
  "Psychology",
  "Art & Design",
  "Cooking",
  "Travel",
  "Poetry",
  "Drama / Plays",
  "Comics & Graphic Novels",
  "Reference Books",
  "Educational Books",
  "Study Guides",
  "Other",
];

/**
 * Get categories for a specific book type
 */
export const getCategoriesByBookType = (
  bookType: "school" | "university" | "reader"
): string[] => {
  switch (bookType) {
    case "school":
      return SCHOOL_CATEGORIES.sort((a, b) => a.localeCompare(b));
    case "university":
      return UNIVERSITY_CATEGORIES.sort((a, b) => a.localeCompare(b));
    case "reader":
      return READER_CATEGORIES.sort((a, b) => a.localeCompare(b));
    default:
      return READER_CATEGORIES.sort((a, b) => a.localeCompare(b));
  }
};
