export const CREATE_LISTING_CATEGORIES: string[] = [
  "Fiction",
  "Mystery & Thriller",
  "Science Fiction",
  "Fantasy",
  "Romance",
  "Adventure",
  "Historical Fiction",
  "Horror",
  "Young Adult",
  "Children's Books",
  "Self-Help",
  "Wellness & Mind",
  "Fitness & Health",
  "Memoir & Biography",
  "History",
  "Science",
  "Business & Economics",
  "Technology",
  "Psychology",
  "Art & Design",
  "Cooking",
  "Travel",
  "Poetry",
  "Drama / Plays",
  "Comics & Graphic Novels",
  "Reference Books",
  "Educational Books",
  "Study Guides",
  "Other",
];
