// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const getSafeEnvVar = (key: string, fallback: string) => {
  const value = import.meta.env[key];
  return (value && value !== "undefined" && value.trim() !== "") ? value : fallback;
};

const SUPABASE_URL = getSafeEnvVar("VITE_SUPABASE_URL", "https://kbpjqzaqbqukutflwixf.supabase.co");
const SUPABASE_ANON_KEY = getSafeEnvVar("VITE_SUPABASE_ANON_KEY", "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImticGpxemFxYnF1a3V0Zmx3aXhmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc1NjMzNzcsImV4cCI6MjA2MzEzOTM3N30.3EdAkGlyFv1JRaRw9OFMyA5AkkKoXp0hdX1bFWpLVMc");

// Validate Supabase configuration before creating client
const validateSupabaseConfig = () => {
  if (!SUPABASE_URL || SUPABASE_URL.trim() === "") {
    throw new Error("VITE_SUPABASE_URL is required.");
  }
  if (!SUPABASE_ANON_KEY || SUPABASE_ANON_KEY.trim() === "") {
    throw new Error("VITE_SUPABASE_ANON_KEY is required.");
  }
  return SUPABASE_ANON_KEY.replace(/\s+/g, "");
};

// Validate configuration and get clean API key
const cleanApiKey = validateSupabaseConfig();

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Global singleton pattern to prevent multiple client instances
let supabaseInstance: any = null;

// Create or return existing Supabase client instance
const createSupabaseClient = () => {
  if (supabaseInstance) {
    return supabaseInstance;
  }

  supabaseInstance = createClient<Database>(
    SUPABASE_URL,
    cleanApiKey,
    {
      auth: {
        autoRefreshToken: true,
        persistSession: true,
        detectSessionInUrl: true,
        flowType: "pkce",
        // Better error handling for failed auth attempts
        debug: import.meta.env.DEV,
      },
      realtime: {
        // Enhanced WebSocket configuration for better reliability
        params: {
          eventsPerSecond: 10,
        },
        // Add heartbeat to keep connections alive
        heartbeatIntervalMs: 30000,
        // Reconnection settings with limited attempts
        reconnectAfterMs: (retries: number) => {
          if (retries >= 5) {
            return 60000; // Stop reconnecting frequently after 5 retries
          }
          const delay = Math.min(1000 * Math.pow(2, retries), 10000);
          return delay;
        },
        // Increase timeout for slower connections
        timeout: 20000,
        logger: undefined,
      },
      global: {
        headers: {
          'X-Client-Info': 'rebooked-marketplace',
        },
      },
    },
  );

  return supabaseInstance;
};

// Export the singleton instance
export const supabase = createSupabaseClient();
